
@baseurl = http://127.0.0.1:8083

// 健康检查
GET {{baseurl}}/healthz

###
// 服务探活 
GET {{baseurl}}/ready

###
// 测试接口
GET {{baseurl}}/test
    # ?table=bs_no
    ?table=bs_sth_task

### 创建定时任务
POST {{baseurl}}/admin/jobs/add

{
  "name": "echooo",
  "type": "http",
  "schedule_type": "cron",
  "cron_expr": "0 * * * * ?",
  "execute_at": "",
  "payload": "{\"method\":\"GET\",\"url\":\"http://127.0.0.1:8083/\"}",
  "timeout_sec": 300
}

### 列出所有定时任务

GET {{baseurl}}/admin/jobs/list

### 预览策略将执行的 SQL(kind: ttl / retry)
POST {{baseurl}}/admin/tabledata/parsesql

{
  "id": 1,
  "kind": "ttl"
}

